name: accountant
description: A Flutter project for Plain Text Accounting based on Ledger.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  file_picker: ">=4.3.0 < 5.0.0"
  provider: ">=6.0.2 < 7.0.0"
  intl: ^0.17.0
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  # permission_handler: ^9.2.0

dev-dependencies:
  hive_generator: ^1.1.3
  build_runner: ^2.1.11
  
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
